#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-site-2-deployment
spec:
  selector:
    matchLabels:
      app: demo-site-2-server
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-site-2-server
    spec:
      containers:
        - name: demo-site-2-container
          #image: gcr.io/tensorflow-serving/resnet
          image: docker.io/danoman17/demo-site-2:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo-site-2-service
  name: demo-site-2-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: demo-site-2-server
  type: LoadBalancer
